openapi: 3.0.1
info:
  title: p4pa-workflow-hub
  description: Api and Models
  version: 0.0.1
servers:
  - url: "http://localhost:8080/workflowhub"
paths:
  /workflow/debt-position:
    post:
      tags:
        - DebtPosition
      operationId: createDpSync
      description: Create a debt position sync.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DebtPositionRequestDTO'
      responses:
        '200':
          description: "Debt position created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowCreatedDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowErrorDTO'
  /workflow/debt-position/aca:
    post:
      tags:
        - DebtPosition
      operationId: createDpSyncAca
      description: Create a debt position sync in Aca.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DebtPositionRequestDTO'
      responses:
        '200':
          description: "Debt position Aca created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowCreatedDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowErrorDTO'
  /ingestion-flow/payments-reporting/{ingestionFlowFileId}:
    post:
      tags:
        - IngestionFlow
      operationId: ingestPaymentsReportingFile
      summary: Payments reporting flow file ingestion
      description: It will start the Payments Reporting flow file ingestion
        returning its workflowId

      parameters:
        - name: ingestionFlowFileId
          in: path
          required: true
          description: The unique identifier of the ingestion File.
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: "Payment Ingestion Workflow created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowCreatedDTO'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowErrorDTO'
  /ingestion-flow/treasury/opi/{ingestionFlowFileId}:
    post:
      tags:
        - IngestionFlow
      operationId: ingestTreasuryOpi
      summary: Treasury OPI ingestion
      description: It will start the Treasury OPI ingestion
        returning its workflowId
      parameters:
        - name: ingestionFlowFileId
          in: path
          required: true
          description: The unique identifier of the ingestion flow File.
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: "Treasury OPI Ingestion Workflow created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowCreatedDTO'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowErrorDTO'
  /classification/transfer/{orgId}:
    post:
      tags:
        - Classification
      operationId: transferClassification
      summary: Transfer classification
      description: It will Processes Transfer classification based on the provided parameters
        returning its workflowId
      parameters:
        - name: orgId
          in: path
          required: true
          description: the unique identifier of the organization.
          schema:
            type: integer
            format: int64
        - name: iuv
          in: query
          required: true
          description: the unique identifier of the payment (IUV).
          schema:
            type: string
        - name: iur
          in: query
          required: true
          description: the identifier of the receipt associated with the payment.
          schema:
            type: string
        - name: transferIndex
          in: query
          required: true
          description: the index of the transfer to be classified.
          schema:
            type: integer
      responses:
        '201':
          description: "Treasury OPI Ingestion Workflow created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowCreatedDTO'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowErrorDTO'
  /workflows/{workflowId}/status:
    get:
      tags:
        - Workflow
      operationId: getWorkflowStatus
      summary: Get Workflow Status
      description: Retrieve the current status of a Temporal workflow by its ID.
      parameters:
        - name: workflowId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Workflow status retrieved successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStatusDTO'
        '404':
          description: "Workflow not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowErrorDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowErrorDTO'
security:
  - BearerAuth: [ ]
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    WorkflowCreatedDTO:
      type: object
      properties:
        workflowId:
          type: string
    WorkflowErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - WORKFLOW_NOT_FOUND
            - WORKFLOW_GENERIC_ERROR
        message:
          type: string
    WorkflowStatusDTO:
      type: object
      required:
        - workflowId
      properties:
        workflowId:
          type: string
        status:
          type: string
    DebtPositionRequestDTO:
      required:
        - organizationId
        - debtPositionTypeOrgId
        - paymentOptions
      type: object
      properties:
        debtPositionId:
          type: integer
          format: int64
        iupdOrg:
          type: string
        description:
          type: string
        status:
          $ref: "#/components/schemas/DebtPositionRequestStatus"
        ingestionFlowFileId:
          type: integer
          format: int64
        ingestionFlowFileLineNumber:
          type: integer
          format: int64
        organizationId:
          type: integer
          format: int64
        debtPositionTypeOrgId:
          type: integer
          format: int64
        notificationDate:
          type: string
          format: date-time
        validityDate:
          type: string
          format: date-time
        flagIuvVolatile:
          type: boolean
        creationDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
        paymentOptions:
          type: array
          items:
            $ref: "#/components/schemas/PaymentOptionRequestDTO"
    PaymentOptionRequestDTO:
      required:
        - installments
        - totalAmountCents
        - paymentOptionType
      type: object
      properties:
        paymentOptionId:
          type: integer
          format: int64
        debtPositionId:
          type: integer
          format: int64
        totalAmountCents:
          type: integer
          format: int64
        status:
          $ref: "#/components/schemas/PaymentOptionRequestStatus"
        multiDebtor:
          type: boolean
        dueDate:
          type: string
          format: date-time
        description:
          type: string
        paymentOptionType:
          type: string
          enum:
            - SINGLE_INSTALLMENT
            - INSTALMENTS
            - DOWN_PAYMENT
        installments:
          type: array
          items:
            $ref: "#/components/schemas/InstallmentRequestDTO"
    InstallmentRequestDTO:
      required:
        - amountCents
        - debtor
        - remittanceInformation
        - transfers
      type: object
      properties:
        installmentId:
          type: integer
          format: int64
        paymentOptionId:
          type: integer
          format: int64
        status:
          $ref: "#/components/schemas/InstallmentRequestStatus"
        iupdPagopa:
          type: string
        iud:
          type: string
        iuv:
          type: string
        iur:
          type: string
        iuf:
          type: string
        nav:
          type: string
        dueDate:
          type: string
          format: date-time
        paymentTypeCode:
          type: string
        amountCents:
          type: integer
          format: int64
        notificationFeeCents:
          type: integer
          format: int64
        remittanceInformation:
          type: string
        humanFriendlyRemittanceInformation:
          type: string
        balance:
          type: string
        legacyPaymentMetadata:
          type: string
        debtor:
          $ref: "#/components/schemas/PersonRequestDTO"
        transfers:
          type: array
          items:
            $ref: "#/components/schemas/TransferRequestDTO"
        creationDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
    TransferRequestDTO:
      required:
        - amountCents
        - category
        - orgFiscalCode
        - orgName
        - remittanceInformation
      type: object
      properties:
        transferId:
          type: integer
          format: int64
        installmentId:
          type: integer
          format: int64
        orgFiscalCode:
          type: string
        orgName:
          type: string
        amountCents:
          type: integer
          format: int64
        remittanceInformation:
          type: string
        stampType:
          type: string
        stampHashDocument:
          type: string
        stampProvincialResidence:
          type: string
        iban:
          type: string
        postalIban:
          type: string
        category:
          type: string
        transferIndex:
          type: integer
          format: int64
    ReceiptRequestDTO:
      type: object
      required:
        - receiptSource
        - paymentReceiptId
        - noticeNumber
        - orgFiscalCode
        - outcome
        - creditorReferenceId
        - paymentAmountCents
        - description
        - companyName
        - idPsp
        - pspCompanyName
        - idChannel
        - channelDescription
        - debtor
        - payer
      properties:
        receiptId:
          type: integer
          format: int64
        installmentId:
          type: integer
          format: int64
        ingestionFlowFileId:
          type: integer
          format: int64
        receiptOrigin:
          type: string
        paymentReceiptId:
          type: string
        noticeNumber:
          type: string
        paymentNote:
          type: string
        orgFiscalCode:
          type: string
        outcome:
          type: string
        creditorReferenceId:
          type: string
        paymentAmountCents:
          type: integer
          format: int64
        description:
          type: string
        companyName:
          type: string
        officeName:
          type: string
        idPsp:
          type: string
        pspFiscalCode:
          type: string
        pspPartitaIva:
          type: string
        pspCompanyName:
          type: string
        idChannel:
          type: string
        channelDescription:
          type: string
        paymentMethod:
          type: string
        feeCents:
          type: integer
          format: int64
        paymentDateTime:
          type: string
          format: date-time
        applicationDate:
          type: string
          format: date-time
        transferDate:
          type: string
          format: date-time
        standin:
          type: boolean
        debtor:
          $ref: "#/components/schemas/PersonRequestDTO"
        payer:
          $ref: "#/components/schemas/PersonRequestDTO"
        creationDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
    PersonRequestDTO:
      required:
        - email
        - fullName
        - entityType
        - fiscalCode
      type: object
      properties:
        entityType:
          type: string
        fiscalCode:
          type: string
        fullName:
          type: string
        address:
          type: string
        civic:
          type: string
        postalCode:
          type: string
        location:
          type: string
        province:
          type: string
        nation:
          type: string
        email:
          type: string
    DebtPositionRequestStatus:
      type: string
      enum:
        - TO_SYNC
        - REPORTED
        - PAID
        - PARTIALLY_PAID
        - CANCELLED
        - INVALID
        - EXPIRED
        - UNPAID
        - DRAFT
    PaymentOptionRequestStatus:
      type: string
      enum:
        - TO_SYNC
        - REPORTED
        - PAID
        - PARTIALLY_PAID
        - CANCELLED
        - INVALID
        - EXPIRED
        - UNPAID
        - DRAFT
    InstallmentRequestStatus:
      type: string
      enum:
        - TO_SYNC
        - REPORTED
        - PAID
        - CANCELLED
        - INVALID
        - EXPIRED
        - UNPAID
        - DRAFT

