openapi: 3.0.1
info:
  title: p4pa-workflow-hub
  description: Api and Models
  version: 0.0.1
servers:
  - url: "http://localhost:8080/workflowhub"
paths:
  /PaymentIngestionWF/{ingestionFileId}:
    post:
      tags:
        - WorkflowHub
      operationId: createPaymentIngestionWF
      summary: Create a Payment Ingestion Workflow
      description: Create a Payment Ingestion Workflow by its ingestionFileId and
        return the workflowId

      parameters:
        - name: ingestionFileId
          in: path
          required: true
          description: The unique identifier of the ingestion File.
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: "Payment Ingestion Workflow created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowCreatedDTO'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowErrorDTO'
components:
  schemas:
    WorkflowCreatedDTO:
      type: object
      properties:
        workflowId:
          type: string
    WorkflowErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - WORKFLOW_NOT_FOUND
            - WORKFLOW_GENERIC_ERROR
        message:
          type: string
