openapi: 3.1.0
info:
  title: p4pa-workflow-hub
  description: Api and Models
  version: 0.0.1
servers:
  - url: "http://localhost:8080/workflowhub"
paths:
  /PaymentIngestionWF/{ingestionFileId}:
    post:
      tags:
        - WorkflowHub
      operationId: createPaymentIngestionWF
      summary: Create a Payment Ingestion Workflow
      description: Create a Payment Ingestion Workflow by its ingestionFileId and
        return the workflowId

      parameters:
        - name: ingestionFileId
          in: path
          required: true
          description: The unique identifier of the ingestion File.
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: "Payment Ingestion Workflow created successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  workflowId:
                    type: string
                    example: 'wf12345678'
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
