openapi: 3.0.1
info:
  title: p4pa-workflow-hub
  description: Api and Models
  version: 0.0.1
servers:
  - url: "http://localhost:8080/workflowhub"
paths:
  /ingestion-flow/payments-reporting/{ingestionFlowFileId}:
    post:
      tags:
        - IngestionFlow
      operationId: ingestPaymentsReportingFile
      summary: Payments reporting flow file ingestion
      description: It will start the Payments Reporting flow file ingestion
        returning its workflowId

      parameters:
        - name: ingestionFlowFileId
          in: path
          required: true
          description: The unique identifier of the ingestion File.
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: "Payment Ingestion Workflow created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowCreatedDTO'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowErrorDTO'
  /workflows/{workflowId}/status:
    get:
      tags:
        - Workflow
      operationId: getWorkflowStatus
      summary: Get Workflow Status
      description: Retrieve the current status of a Temporal workflow by its ID.
      parameters:
        - name: workflowId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Workflow status retrieved successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStatusDTO'
        '404':
          description: "Workflow not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowErrorDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowErrorDTO'

components:
  schemas:
    WorkflowCreatedDTO:
      type: object
      properties:
        workflowId:
          type: string
    WorkflowErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - WORKFLOW_NOT_FOUND
            - WORKFLOW_GENERIC_ERROR
        message:
          type: string
    WorkflowStatusDTO:
      type: object
      required:
         - workflowId
      properties:
        workflowId:
          type: string
        status:
          type: string
